CREATE TABLE [dbo].[Characters]
(
	[CharacterId] INT NOT NULL IDENTITY(1, 1) PRIMARY KEY, 
    [AccountId] INT NOT NULL, 
    [Name] VARCHAR(30) NOT NULL, 
    [Level] INT NOT NULL, 
    [MaxHp] INT NOT NULL, 
    [CurHp] INT NOT NULL, 
    [MaxCp] INT NOT NULL, 
    [CurCp] INT NOT NULL, 
    [MaxMp] INT NOT NULL, 
    [CurMp] INT NOT NULL, 
    [Face] TINYINT NOT NULL, 
    [HairStyle] TINYINT NOT NULL, 
    [HairColor] TINYINT NOT NULL, 
    [Sex] BIT NOT NULL, 
	[Heading] INT NOT NULL,
    [X] INT NOT NULL, 
    [Y] INT NOT NULL, 
    [Z] INT NOT NULL, 
    [Exp] BIGINT NOT NULL, 
    [ExpBeforeDeath] BIGINT NOT NULL, 
    [Sp] INT NOT NULL, 
    [Karma] INT NOT NULL, 
    [PvpKills] INT NOT NULL, 
    [PkKills] INT NOT NULL, 
    [Race] TINYINT NOT NULL, 
    [ClassId] INT NOT NULL, 
    [BaseClass] INT NOT NULL, 
    [DeleteTime] DATETIME2 NULL, 
    [CanCraft] INT NOT NULL, 
    [Title] VARCHAR(50) NULL, 
    [RecHave] INT NOT NULL, 
    [RecLeft] INT NOT NULL, 
    [AccessLevel] INT NOT NULL, 
    [Online] INT NOT NULL, 
    [OnlineTime] INT NOT NULL, 
    [CharSlot] INT NOT NULL, 
    [LastAccess] DATETIME2 NULL, 
    [PunishLevel] INT NOT NULL, 
    [PowerGrade] INT NOT NULL, 
    [Nobless] BIT NOT NULL, 
    [Hero] BIT NOT NULL, 
    [LastRecomDate] DATETIME2 NULL, 
    CONSTRAINT [FK_Characters_Accounts] FOREIGN KEY ([AccountId]) REFERENCES [Accounts]([AccountId]), 
    CONSTRAINT [AK_Characters_Name] UNIQUE ([Name])
)

GO

CREATE INDEX [IX_Characters_AccountId] ON [dbo].[Characters] ([AccountId])
