CREATE TABLE [dbo].[Weapons]
(
	[WeaponId] INT NOT NULL PRIMARY KEY, 
    [Name] VARCHAR(70) NOT NULL, 
    [BodyPart] TINYINT NOT NULL, 
    [Crystallizable] BIT NOT NULL, 
    [Weight] INT NOT NULL, 
    [Soulshots] INT NOT NULL, 
    [Spiritshots] INT NOT NULL, 
    [CrystalType] TINYINT NOT NULL, 
    [Pdam] INT NOT NULL, 
    [RndDam] INT NOT NULL, 
    [WeaponType] INT NOT NULL, 
    [Critical] INT NOT NULL, 
    [HitModify] INT NOT NULL, 
    [AvoidModify] INT NOT NULL, 
    [ShieldDef] INT NOT NULL, 
    [ShieldDefRate] INT NOT NULL, 
    [AtkSpeed] INT NOT NULL, 
    [MpConsume] INT NOT NULL, 
    [Mdam] INT NOT NULL, 
    [Duration] INT NOT NULL, 
    [Price] INT NOT NULL, 
    [CrystalCount] INT NOT NULL, 
    [Sellable] BIT NOT NULL, 
    [Dropable] BIT NOT NULL, 
    [Destroyable] BIT NOT NULL, 
    [Tradeable] BIT NOT NULL, 
    [ItemSkillId] INT NOT NULL, 
    [ItemSkillLvl] INT NOT NULL, 
    [Enchant4SkillId] INT NOT NULL, 
    [Enchant4SkillLvl] INT NOT NULL, 
    [OnCastSkillId] INT NOT NULL, 
    [OnCastSkillLvl] INT NOT NULL, 
    [OnCastSkillChance] INT NOT NULL, 
    [OnCritSkillId] INT NOT NULL, 
    [OnCritSkillLvl] INT NOT NULL, 
    [OnCritSkillChance] INT NOT NULL
)
