namespace L2dotNET.GameService.Model.Templates
{
    public enum ObjectCategory
    {
        Warrior,
        Citizen,
        Holything,
        Guard,
        Merchant,
        Teleporter,
        GuildMaster,
        WarehouseKeeper,
        Ownthing,
        PackageKeeper,
        Boss,
        Minion,
        Xmastree,
        Treasure,
        PcTrap,
        Doppelganger,
        Collection,
        WorldTrap,
        GuildCoach,
        Blacksmith,
        Mrkeeper,
        Monrace,
        SiegeAttacker,
        Player,
        Pet,
        Summon
    }
}