namespace L2dotNET.GameService.Model.Templates
{
    public enum TObjectCategory
    {
        warrior,
        citizen,
        holything,
        guard,
        merchant,
        teleporter,
        guild_master,
        warehouse_keeper,
        ownthing,
        package_keeper,
        boss,
        minion,
        xmastree,
        treasure,
        pc_trap,
        doppelganger,
        collection,
        world_trap,
        guild_coach,
        blacksmith,
        mrkeeper,
        monrace,
        siege_attacker,
        player,
        pet,
        summon
    }
}