namespace L2dotNET.Enums
{
    public enum ActionType
    {
        Calc,
        CallSkill,
        Capsule,
        CreateMpcc,
        Dice,
        Equip,
        Fishingshot,
        Harvest,
        HideName,
        KeepExp,
        NickColor,
        None,
        Peel,
        Recipe,
        Seed,
        ShowAdventurerGuideBook,
        ShowHtml,
        ShowSsqStatus,
        SkillMaintain,
        SkillReduce,
        Soulshot,
        Spiritshot,
        StartQuest,
        SummonSoulshot,
        SummonSpiritshot,
        XmasOpen
    }
}