namespace L2dotNET.Enums
{
    public enum ClassIds
    {
        HumanFighter = 0,
        Warrior = 1,
        Gladiator = 2,
        Warlord = 3,
        Knight = 4,
        Paladin = 5,
        DarkAvenger = 6,
        Rogue = 7,
        TreasureHunter = 8,
        Hawkeye = 9,

        HumanMystic = 10,
        HumanWizard = 11,
        Sorcerer = 12,
        Necromancer = 13,
        Warlock = 14,
        Cleric = 15,
        Bishop = 16,
        Prophet = 17,

        ElvenFighter = 18,
        ElvenKnight = 19,
        TempleKnight = 20,
        SwordSinger = 21,
        ElvenScout = 22,
        PlainsWalker = 23,
        SilverRanger = 24,

        ElvenMystic = 25,
        ElvenWizard = 26,
        Spellsinger = 27,
        ElementalSummoner = 28,
        ElvenOracle = 29,
        ElvenElder = 30,

        DarkFighter = 31,
        PalusKnight = 32,
        ShillienKnight = 33,
        Bladedancer = 34,
        Assassin = 35,
        AbyssWalker = 36,
        PhantomRanger = 37,

        DarkMystic = 38,
        DarkWizard = 39,
        Spellhowler = 40,
        PhantomSummoner = 41,
        ShillienOracle = 42,
        ShillienElder = 43,

        OrcFighter = 44,
        OrcRaider = 45,
        Destroyer = 46,
        Monk = 47,
        Tyrant = 48,

        OrcMystic = 49,
        OrcShaman = 50,
        Overlord = 51,
        Warcryer = 52,

        DwarvenFighter = 53,
        Scavenger = 54,
        BountyHunter = 55,
        Artisan = 56,
        Warsmith = 57,
        Duelist = 88,
        Dreadnought = 89,
        PhoenixKnight = 90,
        HellKnight = 91,
        Saggitarius = 92,
        Adventurer = 93,
        Archmage = 94,
        Soultaker = 95,
        ArcanaLord = 96,
        Cardinal = 97,
        Hierophant = 98,

        EvasTemplar = 99,
        SwordMuse = 100,
        WindRider = 101,
        MoonlightSentinel = 102,
        MysticMuse = 103,
        ElementalMaster = 104,
        EvasSaint = 105,

        ShillienTemplar = 106,
        SpectralDancer = 107,
        GhostHunter = 108,
        GhostSentinel = 109,
        StormScreamer = 110,
        SpectralMaster = 111,
        ShillienSaint = 112,

        Titan = 113,
        GrandKhavatari = 114,
        Dominator = 115,
        Doomcryer = 116,

        FortuneSeeker = 117,
        Maestro = 118
    }
}