namespace L2dotNET.Enums
{
    public enum MaterialType
    {
        Steel,
        FineSteel,
        Cotton,
        BloodSteel,
        Bronze,
        Silver,
        Gold,
        Mithril,
        Oriharukon,
        Paper,
        Wood,
        Cloth,
        Leather,
        Bone,
        Horn,
        Damascus,
        Adamantaite,
        Chrysolite,
        Crystal,
        Liquid,
        ScaleOfDragon,
        Dyestuff,
        Cobweb
    }
}