namespace L2dotNET.templates
{
    public enum Race
    {
        Unknown,
        Undead,
        Magiccreature,
        Beast,
        Animal,
        Plant,
        Humanoid,
        Spirit,
        Angel,
        Demon,
        Dragon,
        Giant,
        Bug,
        Fairie,
        Human,
        Elve,
        Darkelve,
        Orc,
        Dwarve,
        Other,
        Nonliving,
        Siegeweapon,
        Defendingarmy,
        Mercenarie
    }
}